import React  from 'react';
import { mount, shallow } from 'enzyme';
import ErrorBoundary from "../src/error/ErrorBoundary";

const ChildWithError = () => null;

describe('<ErrorBoundary> window',()=> {
    test('should match the snapshot', () => {
      const tree = mount(<ErrorBoundary>Test</ErrorBoundary> )
      expect(tree).toMatchSnapshot()
    })
  
    test('displays error message on error generated by child', () => {
      const wrapper = shallow(
        <ErrorBoundary > 
          <ChildWithError />
        </ErrorBoundary> 
        )

      wrapper.find(ChildWithError).simulateError(new Error('No Movies Found!'));
      expect(wrapper.find('h2')).toBeTruthy();
    })
})